<a href="https://colab.research.google.com/github/tareqmahmud-ai/Data-Cleaning/blob/main/Data_Cleaning_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chicago Payroll Data Exercise Solution

Dear Students, <br>
Let's explore real [payroll data of Chicago city](https://www.kaggle.com/chicago/chicago-citywide-payroll-data). This data is available on [kaggle](https://www.kaggle.com) website and can be downloaded using the provided link. However, a copy of dataset is provided in the course material as well. <br>


Please follow the instructions and answer the questions accordingly. <br>
Good luck!<br>

**Links to few similar datasets are given below to explore ang practice your skills.**<br>
&#9758; [City payroll information for all Los Angeles employees since 2013](https://www.kaggle.com/cityofLA/city-payroll-data) <br>
&#9758; [San Francisco city employee salary data](https://www.kaggle.com/kaggle/sf-salaries)<br>
&#9758; [New York City - Citywide Payroll Data](https://www.kaggle.com/new-york-city/nyc-citywide-payroll-data)

**1. Import pandas as pd.**

In [1]:
import pandas as pd

**2. Read City_of_Chicago_Payroll_Data.csv as a dataframe in pay.**

In [2]:
pay = pd.read_csv('/content/City_of_Chicago_Payroll_Data.csv')

**3. Show first five records in your data.**

In [5]:
pay.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN

**3. Get the overview of your data.<br>**

In [6]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
dtypes: float64(1), object(7)
memory usage: 2.0+ MB

Notice that:<br>
`Typical Hours` is the only float type. <br>
`Typical Hours`, `Annual Salary` and `Hourly Rate` have lots of NaN or null values.

**4. How many 'NaN' you have in each column in your data?**<br>
*Hint: use [<code>isnull()</code>](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.isnull.html)*

In [7]:
pay.isnull().sum()

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        24775
Annual Salary         7883
Hourly Rate          24775
dtype: int64

**5. Output the statistics for your dataset.**

In [9]:
pay.describe(include='all')

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
count,32658,32658,32658,32658,32658,7883.000000,24775,7883
unique,32350,1095,36,2,2,NaN,1038,167
top,"HERNANDEZ, JUAN C",POLICE OFFICER,POLICE,F,Salary,NaN,$90024.00,$35.60
freq,5,9393,12973,30676,24775,NaN,2368,1404
mean,NaN,NaN,NaN,NaN,NaN,34.698719,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,9.145553,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN

**6. What are the maximum, minimum and average Typical Hours? (use 'Typical Hours' column)**<br>

In [11]:
print("Maximum Value:", pay['Typical Hours'].max())
print("Maximum Value:", pay['Typical Hours'].min())
print("Maximum Value:", pay['Typical Hours'].mean())

Maximum Value: 40.0
Maximum Value: 10.0
Maximum Value: 34.69871876189268

**7. How many employees are on salary and how many are working on hourly basis?**<br>
*Hint: Group the data on 'Salary or Hourly' column. Instead of whole dataset, you can take the single column as input as well.*

In [13]:
pay['Salary or Hourly'].value_counts()

Salary or Hourly
Salary    24775
Hourly     7883
Name: count, dtype: int64

In [18]:
pay.groupby('Salary or Hourly').count()['Name']

Salary or Hourly
Hourly     7883
Salary    24775
Name: Name, dtype: int64

**8. Which department has maximum no of employees?**

In [22]:
pay['Department'].value_counts().idxmax()

'POLICE'

In [24]:
pay.groupby('Department').count()['Name'].idxmax()

'POLICE'

**9. How many employees are on Salary and how many are on Hourly in the Police department?**

In [25]:
pay[pay['Department']=='POLICE'].value_counts('Salary or Hourly')

Salary or Hourly
Salary    12941
Hourly       32
Name: count, dtype: int64

In [26]:
df = pay[pay['Department']=='POLICE']
df.groupby('Salary or Hourly').count()['Name']

Salary or Hourly
Hourly       32
Salary    12941
Name: Name, dtype: int64

**10. What are the mean, max and min salaries?**<br>
use <code>.str and replace()</code><br>
Create a new column name "Salaries" and separate the number from dollar sign as float .<br>
Hint: [pandas.series.str](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.split.html) and [Stackoverflow link](https://stackoverflow.com/questions/38516481/trying-to-remove-commas-and-dollars-signs-with-pandas-in-python)

In [31]:
pay['Salary'] = pay['Annual Salary'].str.replace('$', '').astype(float)
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
 8   Salary             24775 non-null  float64
dtypes: float64(2), object(7)
memory usage: 2.2+ MB

In [32]:
pay['Salary'].max()

300000.0

In [33]:
pay['Salary'].min()

0.96

In [35]:
print(pay['Salary'].mean())

87512.78024137235

**11. Find an employee who has the maximum salary.**<br>
Don't use the max number you got above, write a code for general condition. <br>
Try with [<code>idxmax()</code>](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.idxmax.html) as well!

In [41]:
#pay['Salary'].idxmax()
#pay.loc[8310]
pay.loc[pay['Salary'].idxmax()].iloc[0]

'EVANS,  GINGER S'

**12. Find an employee who has the minimum salary.**<br>
Use [<code>idxmin()</code>](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.idxmin.html) as well!

In [42]:
pay.loc[pay['Salary'].idxmin()].iloc[0]

'KOCH,  STEVEN '

**13. What are the mean, max and min Hourly Rate?**<br>
use <code>.str and replace()</code><br>
Hint:
Once again, create a new column name "H_Rate" and separate the number from dollar sign as float .<br>

In [48]:
pay['H_Rate'] = pay['Hourly Rate'].str.replace('$', '').astype(float)

In [49]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
 8   Salary             24775 non-null  float64
 9   H_Rate             7883 non-null   float64
dtypes: float64(3), object(7)
memory usage: 2.5+ MB

In [50]:
print(pay['H_Rate'].max())
print(pay['H_Rate'].min())
print(pay['H_Rate'].mean())

96.0
2.65
32.86819231257135

**14. How many employees are getting max Hourly Rate?**

In [61]:
print(pay.groupby('H_Rate').count()['Name'].sort_index(ascending=False).iloc[0])

1

**15. Who is getting max Hourly Rate?**

In [65]:
pay.loc[pay['H_Rate'].idxmax()]['Name']

'JONES,  JOHN W'

**16. How many employees are earning less than the average Hourly Rate?**

In [72]:
pay[pay['H_Rate'] < pay['H_Rate'].mean()].count()['Name']

np.int64(2791)

**17. How many employees are paid hourly and they have full-time job?**

In [78]:
#pay['Full or Part-Time'].unique()
pay[(pay['Salary or Hourly']=='Hourly') & (pay['Full or Part-Time']=='F')].count()['Name']

np.int64(5906)

**18. Find the full-time employees who are working at hourly rate of $10.00?**

In [80]:
pay[(pay['Full or Part-Time']=='F') & (pay['H_Rate']==10)]['Name']

1232        AYALA JR,  JESUS
4522     CERVANTES,  BIANCA A
6476       DAVILA,  ROBERTO A
16474           LEVY,  ETHAN
Name: Name, dtype: object

**19. How many unique Job Titles are there in the data?**

In [83]:
pay['Job Titles'].nunique()

1095

**20. What was the average Salary of the employees in each department?**

In [87]:
pay.groupby('Department')['Salary'].mean().head()

Department
ADMIN HEARNG         78912.947368
ANIMAL CONTRL        66089.684211
AVIATION             76140.018777
BOARD OF ELECTION    56051.142857
BOARD OF ETHICS      94552.500000
Name: Salary, dtype: float64

**21. What is the job title of 'AGAR,  BULENT B'?** please note, there are two spaces between AGAR, and BULENT.

In [89]:
pay[pay['Name'] == 'AGAR,  BULENT B']['Job Titles']

230    CHIEF ENGINEER OF SEWERS
Name: Job Titles, dtype: object

**22. What are the top most common job titles?**

In [100]:
pay['Job Titles'].value_counts().index[0]

'POLICE OFFICER'

**23. How many people have the word 'officer' in their job title? (This is pretty tricky)**

In [101]:
pay['Job Titles'].str.contains('OFFICER', case=False).sum()

np.int64(11101)

In [102]:
def find_string(title):
  if 'officer' in title.lower():
    return True
  else:
    return False

In [104]:
pay['Job Titles'].apply(find_string).sum()

np.int64(11101)

**24. Save the final dataframe to a csv file**

In [105]:
pay.to_csv('final_pay.csv', index=False)

# Great Job!

In [106]:
df = pd.read_csv('/content/final_pay.csv')
df.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,$107790.00,NaN,107790.0,NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,$104628.00,NaN,104628.0,NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,$114324.00,NaN,114324.0,NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,$76932.00,NaN,76932.0,NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,$111474.00,NaN,111474.0,NaN